### ISSUE TITLE
Unable to compile code using cmake

### ISSUE THREAD

**Issue by khGao** [hosseinmoein/DataFrame#234] opened 2023-04-03 08:16 UTC
The questions are as follows.

cmake .. -DCMAKE_BUILD_TYPE=Debug  -DHMDF_BENCHMARKS=1 -DHMDF_EXAMPLES=1 -DHMDF_TESTING=1

-- The CXX compiler identification is GNU 10.3.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for clock_gettime
-- Looking for clock_gettime - found
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
_**-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed**_
-- Looking for pthread_create in pthreads
**_-- Looking for pthread_create in pthreads - not found_**
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/gkh/cpp_da/DataFrame-2.0.0/build

My computer is "Linux ubuntu 5.15.0-69-generic #76~20.04.1-Ubuntu SMP Mon Mar 20 15:54:19 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux".
The version of GCC is "gcc (Ubuntu 10.3.0-1ubuntu1~20.04) 10.3.0".
The version of g++ is "g++ (Ubuntu 10.3.0-1ubuntu1~20.04) 10.3.0".
The version of cmake is "cmake version 3.16.3".
The version if linux is "Ubuntu 20.04.4 LTS".

In the past few weeks, I have looked up a lot of information, but I can't find an answer.
Can you give me a favor?
Thank you !

**Comment by hosseinmoein** [comment] 2023-04-03 12:34
I am not sure what you are asking. Do you fail to compile DataFrame?
In any case, this may help:
https://stackoverflow.com/questions/31948521/building-error-using-cmake-cannot-find-lpthreads

**Comment by khGao** [comment] 2023-04-04 06:40
> I am not sure what you are asking. Do you fail to compile DataFrame? In any case, this may help: https://stackoverflow.com/questions/31948521/building-error-using-cmake-cannot-find-lpthreads

I follow your instructions to use cmake to compile "CMakeLists.txt".The instructions  is "cmake .. -DCMAKE_BUILD_TYPE=Debug -DHMDF_BENCHMARKS=1 -DHMDF_EXAMPLES=1 -DHMDF_TESTING=1".
 
But the result was disappointing. I also checked the link you shared, but it doesn't solve the problem.

I wrote a simple script to determine the problem, as shown in the chart.
I cannot solve the compiling problem.

Do you have any good way to solve this problem?

![problem](https://user-images.githubusercontent.com/129731712/229708401-a6dadef9-7cab-4f70-b426-144fc3743ac1.jpg)

**Comment by khGao** [comment] 2023-04-04 07:08
Hello, sir.
![problem2](https://user-images.githubusercontent.com/129731712/229714904-34f27a5d-d2cb-4b76-a781-90ad97bd64f0.jpg)

There is a question that I forgot to mention before, now upload the screenshot of the question.

**Comment by hosseinmoein** [comment] 2023-04-04 14:30
1. The problem with `fabsl` is fixed in master
2. DataFrame requires C++17 or later
3. I don't know what the issue is with your `pthread` problem. I have never seen to or heard about it. It seems your development tools are not installed properly

**Closed as completed** 2023-04-12 12:24 UTC
Labels: help wanted, Compiling
